apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: app01
        image: ahmedelenany703/solutionapp:f727493f081b7a762fdfc2dc004d138a59a382ce
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 3000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_HOST 
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: USER
          - name: USER_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: user-pass
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_NAME
        
        livenessProbe:
          httpGet:
            path: /
            port: http
        
        readinessProbe:
          httpGet:
            path: /
            port: http

      restartPolicy: Always
