apiVersion: apps/v1
kind: Deployment
metadata:
  name: solution-deployment
  labels:
    app: myapp
  namespace: jenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: solution
        image: ahmedelenany703/solution-app:e6067fc468532c32e5d666ae7f87564a196dae5f
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 3000
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_HOST 
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: USER
          - name: USER_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: user-pass
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: DB_NAME
                
      restartPolicy: Always
