---
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: vpa-db
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: mysql-statefulset
  updatePolicy:
    updateMode: "Auto"  # v 1.33 "beta"
